name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 13.203.161.238
          username: ubuntu
          password: ${{ secrets.SSH_KEY }}
          port: 22
          script: whoami

      
